### PR TITLE
Release fixes for 3.5

### PR DESCRIPTION
**Pull request by dswd**
IMPORTANT: Please do not merge before all following errors are fixed and all tests pass

Errors still to fix:

Postponed errors:
* [missing] rextfv_status_updater does not emit events
* [enhancement] rextfv_status_updater updates elements regardless of state
* [enhancement] better dumpmanager UI
* [bugfix, once] "VNC server did not" start while starting OpenVZ VM
* [bugfix, once] Error executing command 'tc qdisc del root dev tinc344': [1] Cannot find device "tinc344"
* [bugfix, once] "Unsupported action" when adding a custom script

Tests to run:
* Chat tutorial -- passed
* OpenFlow tutorial -- passed
* Backend test cases -- passed
* Hostmanager test cases -- passed
* Test new error reporting -- passed
* Test new SSL-RPC connections -- passed
* Test import/export topologies -- passed

### CODE REVIEW

**Comment by t-gerhard** [comment]
Error Management UI can be found at /dumpmanager. There is an entry in the menu under Hosts/Resources if you have the Debug permission.

**Comment by t-gerhard** [comment]
What I found so far about rextfv_status_updater

* **Creating an element can lead to the editor calling /element/undefined/info** This is a race condition: at the end of IconElement.init, it adds _this_ to the updater. If _this_ has not been filled by the return of element_create, the status updater will use a version without ID.
* **Quickly destroying and removing an element** keeps a copy of the element in the status updater's list. thus, it will try to update it even if it doesn't exist anymore.
* Other problems can be ignored (i.e., don't show an error message).

I will fix these later.
I have no idea why uploading an archive leads to problems. I will investigate this.

* We need to create a much better version of the status updater which avoids unnecessary updates (i.e., removing an element). I suggest including this in the next maintenance release.
* the status updater does not throw events, but tutorials are triggered after each update. We can add a separate trigger in the next realease, but it is not needed for this realease right now.

**Comment by t-gerhard** [comment]
Shouldn't the "VNC server did not start" issue be fixed when we have done the more robust low-level calls?

**Comment by dswd** [comment]
Only KVM has been rewritten so far. This error now only happens for OpenVZ

**Pull request merged**
